[package]
name = "kmeans"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3.1"
image = "0.25.6"
linalg = "0.1.0"
nalgebra = "0.33.2"
num = "0.4.3"
plotters = "0.3.7"
rand = "0.9.1"
rand_distr = "0.5.1"

[profile.release]
debug = true
